version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "github-actions"

  - package-ecosystem: "gradle"
    directory: "/core"
    schedule:
      interval: "daily"
    labels:
      - "core"

  - package-ecosystem: "gradle"
    directory: "/app"
    schedule:
      interval: "daily"
    labels:
      - "app"

  - package-ecosystem: "pip"
    directory: "/crawler"
    schedule:
      interval: "daily"
    labels:
      - "crawler"
