version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/core"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/crawler"
    schedule:
      interval: "weekly"
