version: "3"
services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: axbot
      POSTGRES_PASSWORD: AxbotP@ssword.
      POSTGRES_DB: axbot
    volumes:
      - ./volume/postgres:/var/lib/postgresql/data
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: axbot
      MYSQL_PASSWORD: AxbotP@ssword.
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: axbot
    volumes:
      - ./volume/mysql:/var/lib/mysql
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./volume/rabbitmq/:/var/lib/rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
