name: 报告问题
description: 向开发者报告一个问题。
title: "[Bug]: "
labels: ["bug"]
assignees:
  - axiangcoding
body:
  - type: markdown
    attributes:
      value: |
        感谢您抽出时间向开发者提交错误报告！不过，在提交错误报告前，请您重新确认：
        1. 文档中没有相关的资料或者描述不准确
        2. 经过多次实践均复现问题
        如果以上的条件均满足，请填写本错误报告
  - type: textarea
    id: what-happened
    attributes:
      label: 发生了什么？
      description: 也告诉我们，你期望发生什么？
      placeholder: 例如：机器人的XX功能不能用了
    validations:
      required: true
  - type: textarea
    id: how-to-do
    attributes:
      label: 问题重现的步骤
      description: 请尽可能描述清楚能重现问题的步骤
      placeholder: | 
        例如：
        这样做可以复现问题：
        1. xxx
        2. xxx
        3. xxx
  - type: dropdown
    id: platform
    attributes:
      label: 问题相关的机器人平台
      description: 问题发送在哪些机器人平台上？如果和平台不相关，可以为空
      options:
        - KOOK
        - QQ频道
      multiple: true
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: 有关的运行日志
      description: 如果问题发生和项目运行相关，请复制并粘贴任何相关的日志输出。这个输入栏目会自动格式化为代码，因此不需要反引号。
      render: shell
  - type: textarea
    id: addition
    attributes:
      label: 额外的信息
      description: 你可以在这里贴上截图，或者更详细的描述
