name: Feature Request 功能请求
description: File a feature request 报告一个功能请求
title: "[Feature]: "
labels: ["enhancement"]
assignees:
  - axiangcoding
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request! 感谢您抽出时间填写此功能请求！
  - type: textarea
    id: what-need
    attributes:
      label: What feature or enhancement do you need? 你需要什么功能或增强？
      description: Also tell us, what did you expect to happen? 也告诉我们，你期望发生什么？
      placeholder: Tell us what you need! 告诉我们你需要什么
      value:
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Bot Platform needs to be supported 哪些机器人平台需要支持
      description: select all you need 选择你需要的所有
      options:
        - Kook
        - Cqhttp
      multiple: true
    validations:
      required: true
  - type: textarea
    id: addition
    attributes:
      label: Addition info 额外的信息
      description: Anything else you want to add? 其他你想补充的吗？
