# All sections containing keys in this configuration file are intended for testing purposes only and should never be used in a production environment!
server:
  port: 8888
  servlet:
    context-path: /api
  shutdown: graceful

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/axbot
    username: axbot
    password: AxbotP@ssword.
  data:
    redis:
      url: redis://localhost:6379
      repositories:
        enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

logging:
  file:
    name: ./logs/axbot.log
    path: ./logs/

bot:
  censor:
    enabled: true
    qiniu:
      access-token:
      secret-token:
  trigger-message-prefix:
    - axbot
    - .axbot
  kook:
    enabled: true
    bot-token:
    verify-token:
  cqhttp:
    enabled: true
    base-url: http://localhost:5700/
    secret:
