server:
  port: 8888
  servlet:
    context-path: /api

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/axbot
    username: axbot
    password: AxbotP@ssword.
  data:
    redis:
      url: redis://localhost:6379
      lettuce:
        pool:
          enabled: true
  jackson:
    property-naming-strategy: SNAKE_CASE


logging:
  file:
    name: ./logs/axbot.log
    path: ./logs/
